version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ems
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./src/main/resources/ems.sql:/docker-entrypoint-initdb.d/ems.sql

  app:
    image: ems-image
    environment:
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

volumes:
  db-data:
